[project]
name = "voting-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.95",
    "django>=6.1.1",
    "django-storages[s3]>=1.14.6",
    "django-unfold>=0.106.1",
    "gunicorn>=26.2.0",
    "pillow>=12.3.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "whitenoise>=6.12.0",
]
