# Generated by Django 6.1.1 on 2026-09-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_dedupe_candidates'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidate',
            name='unique_student_position',
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('student',), name='unique_candidate_per_student'),
        ),
    ]
